### ISSUE TITLE
Error when trying to merge a PR that's already merged

### ISSUE THREAD

**Issue by Mariatta** [python/miss-islington#131]
The error can be caught.

Log:
Aug 09 15:03:52 miss-islington app/web.1:  GH delivery ID 19e9ae34-9c20-11e8-8119-f84026ce9ae3 
Aug 09 15:03:53 miss-islington heroku/router:  at=info method=POST path="/" host=miss-islington.herokuapp.com request_id=61fe7df2-985b-4549-bbaf-8a0d34964361 fwd="192.30.252.34" dyno=web.1 connect=1ms service=2394ms status=500 bytes=187 protocol=https 
Aug 09 15:03:54 miss-islington app/web.1:  Traceback (most recent call last): 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/miss_islington/__main__.py", line 40, in main 
Aug 09 15:03:54 miss-islington app/web.1:      await router.dispatch(event, gh) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/routing.py", line 80, in dispatch 
Aug 09 15:03:54 miss-islington app/web.1:      await callback(event, *args, **kwargs) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/miss_islington/status_change.py", line 22, in check_status 
Aug 09 15:03:54 miss-islington app/web.1:      await check_ci_status_and_approval(gh, sha, leave_comment=True) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/miss_islington/status_change.py", line 80, in check_ci_status_and_approval 
Aug 09 15:03:54 miss-islington app/web.1:      await merge_pr(gh, pr_number, sha) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/miss_islington/status_change.py", line 96, in merge_pr 
Aug 09 15:03:54 miss-islington app/web.1:      "merge_method": "squash", 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/abc.py", line 104, in put 
Aug 09 15:03:54 miss-islington app/web.1:      data, _ = await self._make_request("PUT", url, url_vars, data, accept) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/abc.py", line 66, in _make_request 
Aug 09 15:03:54 miss-islington app/web.1:      data, self.rate_limit, more = sansio.decipher_response(*response) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/sansio.py", line 310, in decipher_response 
Aug 09 15:03:54 miss-islington app/web.1:      raise exc_type(*args) 
Aug 09 15:03:54 miss-islington app/web.1:  gidgethub.BadRequest: Base branch was modified. Review and try the merge again. 
Aug 09 15:03:54 miss-islington app/web.1:  Traceback (most recent call last): 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/miss_islington/__main__.py", line 40, in main 
Aug 09 15:03:54 miss-islington app/web.1:      await router.dispatch(event, gh) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/routing.py", line 80, in dispatch 
Aug 09 15:03:54 miss-islington app/web.1:      await callback(event, *args, **kwargs) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/miss_islington/status_change.py", line 30, in pr_reviewed 
Aug 09 15:03:54 miss-islington app/web.1:      await check_ci_status_and_approval(gh, sha) 
Aug 09 15:03:54 miss-islington app/web.1:    File "/app/miss_islington/status_change.py", line 80, in check_ci_status_and_approval 
Aug 09 15:03:54 miss-islington heroku/router:  at=info method=POST path="/" host=miss-islington.herokuapp.com request_id=e469ce6a-3e94-46d5-8a34-8431731e8dfd fwd="192.30.252.34" dyno=web.1 connect=0ms service=2719ms status=500 bytes=187 protocol=https

**Comment by Mariatta** [comment]
Different errror message:

Aug 31 15:52:39 miss-islington app/web.1: Traceback (most recent call last): 
Aug 31 15:52:39 miss-islington app/web.1:    File "/app/miss_islington/__main__.py", line 40, in main 
Aug 31 15:52:39 miss-islington app/web.1:     await router.dispatch(event, gh) 
Aug 31 15:52:39 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/routing.py", line 80, in dispatch 
Aug 31 15:52:39 miss-islington app/web.1:     await callback(event, *args, **kwargs) 
Aug 31 15:52:39 miss-islington app/web.1:    File "/app/miss_islington/delete_branch.py", line 14, in delete_branch 
Aug 31 15:52:39 miss-islington app/web.1:     await gh.delete(url) 
Aug 31 15:52:39 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/abc.py", line 109, in delete 
Aug 31 15:52:39 miss-islington app/web.1:     await self._make_request("DELETE", url, url_vars, data, accept) 
Aug 31 15:52:39 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/abc.py", line 66, in _make_request 
Aug 31 15:52:39 miss-islington app/web.1:     data, self.rate_limit, more = sansio.decipher_response(*response) 
Aug 31 15:52:39 miss-islington app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/sansio.py", line 299, in decipher_response 
Aug 31 15:52:39 miss-islington app/web.1:     raise InvalidField(errors, message) 
Aug 31 15:52:39 miss-islington app/web.1: gidgethub.InvalidField: Reference does not exist

**Comment by AA-Turner** [comment]
We now use GH auto merge
